version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t seanbrandt/git-sync:${CIRCLE_BRANCH}_$(echo $CIRCLE_SHA1 | cut -c -7) .

      - run: docker push seanbrandt/git-sync:${CIRCLE_BRANCH}_$(echo $CIRCLE_SHA1 | cut -c -7)

